# Generated by Django 5.1.6 on 2025-02-18 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('reset_password_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Token de restablecimiento de contraseña')),
                ('reset_password_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración del token de restablecimiento')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
