# Generated by Django 5.1.6 on 2025-02-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre_categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha_actualizacion')),
            ],
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='fecha_publicacion',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='notas.category'),
        ),
    ]
